"""empty message

Revision ID: 3084afea7035
Revises: 4a04947c2455
Create Date: 2018-04-21 16:29:58.760759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3084afea7035'
down_revision = '4a04947c2455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hash', sa.Column('pass_id', sa.INTEGER(), nullable=False))
    op.drop_constraint('hash_ibfk_1', 'hash', type_='foreignkey')
    op.create_foreign_key(None, 'hash', 'pass', ['pass_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hash', 'upload_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hash', sa.Column('upload_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hash', type_='foreignkey')
    op.create_foreign_key('hash_ibfk_1', 'hash', 'upload', ['upload_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hash', 'pass_id')
    # ### end Alembic commands ###
