"""empty message

Revision ID: 7a57bd921158
Revises: 3084afea7035
Create Date: 2018-04-27 17:26:30.246240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a57bd921158'
down_revision = '3084afea7035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sub_a', sa.INTEGER(), nullable=False),
    sa.Column('sub_b', sa.INTEGER(), nullable=False),
    sa.Column('pass_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_a'], ['submission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_b'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
